### ISSUE TITLE
test not running

### ISSUE THREAD

**Issue by 0107shashankgarg** [selenide-examples/selenoid-sample#1]
Hi I Cloned the project and ran mvn test 
error :
 Running org.selenide.examples.selenoid.FileDownloadTest
[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.709 s <<< FAILURE! - in org.selenide.examples.selenoid.FileDownloadTest
[ERROR] download  Time elapsed: 1.692 s  <<< ERROR!
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'shashankgarg', ip: '192.168.0.58', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
selenide.remote: http://localhost:4444/wd/hub
Driver info: driver.version: SelenideDriver
selenide.url: https://the-internet.herokuapp.com/download
selenide.baseUrl: http://localhost:8080
        at org.selenide.examples.selenoid.FileDownloadTest.download(FileDownloadTest.java:29)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4444
        at org.selenide.examples.selenoid.FileDownloadTest.download(FileDownloadTest.java:29)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at org.selenide.examples.selenoid.FileDownloadTest.download(FileDownloadTest.java:29)

[INFO] Running org.selenide.examples.selenoid.ClipboardTest
[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.04 s <<< FAILURE! - in org.selenide.examples.selenoid.ClipboardTest

**Comment by 0107shashankgarg** [comment]
please ignore
